#!/usr/bin/perl -w
# nagios: +epn

######################################### check_snmp_linux_load #####################################
# FUNCTION :	Retrieve the system load of a Linux host through SNMP.
#
# AUTHOR :		Matthieu FOURNET (matthieu.fournet@orange.com)
# LICENSE :		GPL - http://www.fsf.org/licenses/gpl.txt
#
# NOTES :		This plugin always returns an 'OK' status (values are just for graphs.)
#
# COMMAND LINE :
#	check_snmp_linux_load -H [hostName] --snmp-version [version] --rocommunity [community] --snmp-debug
#
# VERSION :		20130501
########################################## ##########################################################


########################################## ##########################################################
# SUBS
########################################## ##########################################################
sub getSystemLoad
	{
	my $nagiosPluginSnmp = shift;

	my $linux_load_table	= '1.3.6.1.4.1.2021.10.1';		# net-snmp load table
	my $linux_load_name		= '1.3.6.1.4.1.2021.10.1.2';	# text 'Load-1','Load-5','Load-15'
	my $linux_load_load		= '1.3.6.1.4.1.2021.10.1.3';	# effective load table

	my $results = $nagiosPluginSnmp->walk($linux_load_table);

	my @load = undef;
	foreach my $key ( keys %{$results->{$linux_load_table}}) {
		Nenm::Utils::debug("OID : $key, Desc : $results->{$linux_load_table}->{$key}");
		if ( $key =~ /$linux_load_name/ ) {
			$key =~ /.*\.(\d+)$/;
			my $index = '.'.$1;
			$load[0]	= $results->{$linux_load_table}->{$linux_load_load.$index} if ($results->{$linux_load_table}->{$key} eq 'Load-1');
			$load[1]	= $results->{$linux_load_table}->{$linux_load_load.$index} if ($results->{$linux_load_table}->{$key} eq 'Load-5');
			$load[2]	= $results->{$linux_load_table}->{$linux_load_load.$index} if ($results->{$linux_load_table}->{$key} eq 'Load-15');
			}
		}
	Nenm::Utils::debug('System Load 1m  : '.$load[0]);
	Nenm::Utils::debug('System Load 5m  : '.$load[1]);
	Nenm::Utils::debug('System Load 15m : '.$load[2]);

	return $load[0], $load[1], $load[2];
	}


########################################## ##########################################################
# main()
########################################## ##########################################################
sub main
	{
	use strict;
	use Nagios::Plugin::SNMP;
	use Nenm::Utils;

	my $LABEL	= 'SYSTEM LOAD';

	# http://search.cpan.org/~maxschube/Nagios-Plugin-SNMP-1.0/lib/Nagios/Plugin/SNMP.pm
	my $plugin	= Nagios::Plugin::SNMP->new( 'shortname' => $LABEL );

	$plugin->getopts;

	$Nenm::Utils::DEBUG = $plugin->opts->get('snmp-debug');

	my $IP = $plugin->opts->get('hostname');

	Nenm::Utils::debug('Checking load ');
	my ($load1, $load5, $load15) = getSystemLoad($plugin);

	my $output_label = "$LABEL ";

	$plugin->add_perfdata (
		label	=> 'load1',
		value	=> $load1,
		uom		=> ''
		);

	$plugin->add_perfdata (
		label	=> 'load5',
		value	=> $load5,
		uom		=> ''
		);

	$plugin->add_perfdata (
		label	=> 'load15',
		value	=> $load15,
		uom		=> ''
		);

	$plugin->nagios_exit (OK, "NO WARN. Load : $load1, $load5, $load15");
	}



########################################## ##########################################################
# Now run !
########################################## ##########################################################
exit main();

########################################## ##########################################################
# POD
########################################## ##########################################################

=pod

=head1 Synopsis

=begin html

<link rel="stylesheet" type="text/css" href="./plugins.css" />
Plugin <span class="pluginName">check_snmp_linux_load</span> : Monitors the system load (as shown by 'top')

=end html




=head1 Dependencies

	use strict;
	use Nagios::Plugin::SNMP;
	use Nenm::Utils;




=head1 Command line

	check_snmp_linux_load -H [host] --snmp-version [version] --rocommunity [community] --snmp-debug

=over 4

=item *

-H : IP address or hostname of Linux server to check

=item *

--snmp-version : explicit ;-)

=item *

--rocommunity : SNMP community

=item *

--snmp-debug : [optional] toggle the debug messages

=back




=head1 Output status

=over 4

=item *

=begin html

<span class="critical">CRITICAL</span> : never (this version takes no WARN / CRIT parameters and make no comparison between measured load and thresholds).

=end html

=item *

=begin html

<span class="warning">WARNING</span> : never (this version takes no WARN / CRIT parameters and make no comparison between measured load and thresholds).

=end html

=item *

=begin html

<span class="ok">OK</span> : Always. To remind admin of that this plugin never warns, the shown status is "OK - NO WARN".

=end html

=item *

=begin html

<span class="unknown">UNKNOWN</span> : (never)

=end html

=back




=head1 Perfdata

=begin html

<span class="perfdata">load1==[avg. load 1min];(no warning value);(no critical value)</span>
<br /><br />
<span class="perfdata">load5==[avg. load 5min];(no warning value);(no critical value)</span>
<br /><br />
<span class="perfdata">load15==[avg. load 15min];(no warning value);(no critical value)</span>

=end html




=head1 Author

Matthieu FOURNET (matthieu.fournet@orange.com)

=cut
