#!/bin/bash

######################################### check_mysql_user_nb_process ###############################
# FUNCTION :    Return the total number of MySQL processes (+alerts on thresholds),
#               and the number of sleeping connections (for graph only)
#
# AUTHOR :      Matthieu FOURNET (fournet.matthieu@gmail.com)
# LICENSE :     GPL - http://www.fsf.org/licenses/gpl.txt
#
# NOTES :       1. running this plugin requires MySQL 'SELECT' grants on 'mysql.*' : grant select on mysql.* to 'shinken';
#               2. this is based on the MySQL 'information_schema.PROCESSLIST', which is available from the 5.? MySQL version
#
# COMMAND LINE :
#               check_mysql_user_nb_process -H <mysqlHost> -u "<mysqlUser>" -p "<mysqlPassword>" -w <warn> -c <crit> -v
#
# VERSION :     20130526
########################################## ##########################################################

currentFolder=$(pwd)
source ${currentFolder}/Functions/Common.sh
source ${currentFolder}/Functions/MySQL.sh


########################################## ##########################################################
# FUNCTIONS
########################################## ##########################################################
#---------------------
# Show the plugin help message.
# ARGUMENTS :   none
# RETURN :      void
#---------------------
function exitShowHelp() {
    cat << GLOUBIBOULGA
    FUNCTION:
        - alert on the number of MySQL processes running (based on "show processlist;")
        - return the number of sleeping processes (no alerts, graphs only)

    USAGE:
        $0 -H <MySQL host> -u <MySQL user> -p <MySQL password> -w <warning> -c <critical>

    OPTIONS:
        -h    Show this message
        -H    MySQL host IP address or DNS name
        -u    MySQL user
        -p    MySQL password
        -w    WARNING treshold
        -c    CRITICAL treshold
        -v    Verbose
GLOUBIBOULGA
    exit $STATE_UNKNOWN
    }


########################################## ##########################################################
# CONFIG
########################################## ##########################################################
OPT_VERBOSE=0

exitCode=$STATE_OK
pluginOutput='MySQL user nb process '
pluginPerfdata=''

tmpFile="./tmp.$$"

mysqlBin=$(which mysql)


########################################## ##########################################################
# USER INPUT VALIDATION
########################################## ##########################################################
while getopts 'hH:u:p:c:w:v' option;do  # http://man.cx/getopts
    case $option in
        h)
            exitShowHelp
            ;;
        H)
            OPT_MYSQLHOST=$OPTARG
            ;;
        u)
            OPT_MYSQLUSER=$OPTARG
            ;;
        p)
            OPT_MYSQLPASSWORD=$OPTARG
            ;;
        c)
            OPT_CRITICAL=$OPTARG
            ;;
        w)
            OPT_WARNING=$OPTARG
            ;;
        v)
            OPT_VERBOSE=1
            ;;
        ?)
            exitShowHelp
            exit
            ;;
     esac
done

if [ $OPT_VERBOSE -eq 1 ]; then
    echo "[DEBUG] Options :
    OPT_MYSQLHOST :     $OPT_MYSQLHOST
    OPT_MYSQLUSER :     $OPT_MYSQLUSER
    OPT_MYSQLPASSWORD : $OPT_MYSQLPASSWORD
    OPT_CRITICAL :      $OPT_CRITICAL
    OPT_WARNING :       $OPT_WARNING
    OPT_VERBOSE :       $OPT_VERBOSE
    tmpFile :           $tmpFile"
fi

# checking options given to plugin
if [ -z $OPT_WARNING ] || [ -z $OPT_CRITICAL ]; then
     exitPlugin '[ERROR] WARNING and CRITICAL parameters are mandatory.' '' 0 $STATE_UNKNOWN
fi

if [ $OPT_WARNING -gt $OPT_CRITICAL ]; then
     exitPlugin '[ERROR] WARNING must be less than CRITICAL.' '' 0 $STATE_UNKNOWN
fi


########################################## ##########################################################
# GETTING METRICS
########################################## ##########################################################
mysqlQuery="SELECT U.user, COUNT(PL.user) as nbProcess FROM mysql.user U LEFT JOIN information_schema.PROCESSLIST PL ON PL.user=U.user GROUP BY U.user ORDER BY COUNT(PL.user) DESC"

$mysqlBin -h $OPT_MYSQLHOST -u $OPT_MYSQLUSER -p"$OPT_MYSQLPASSWORD" -e "$mysqlQuery" > $tmpFile

# Creation of $tmpFile sometimes fails (?). Let's handle it !
[ -f $tmpFile ] || exitPlugin "$tmpFile not found" '' $STATE_UNKNOWN

removeFirstLineOfFile $tmpFile

highestNbProcess=0
highestUser=''

while read line;do
    userName=$(getFieldFromLine "$line" 1)
    nbProcess=$(getFieldFromLine "$line" 2)
    pluginPerfdata=${pluginPerfdata}${userName}'='${nbProcess}';'$OPT_WARNING';'$OPT_CRITICAL' '

    if (( $nbProcess > $highestNbProcess )); then
        highestNbProcess=$nbProcess
        highestUser=$userName
    fi
done < $tmpFile


########################################## ##########################################################
# Cleaning
########################################## ##########################################################
[ -f $tmpFile ] && rm $tmpFile


########################################## ##########################################################
# OUTPUT STATUS + PERFDATA
########################################## ##########################################################
if (( $highestNbProcess < $OPT_WARNING ));then
    exitCode=$STATE_OK
    pluginOutput=$pluginOutput"OK : Max number of processes per user ($highestUser : $highestNbProcess) < Warning ($OPT_WARNING)"
elif (( $highestNbProcess >= $OPT_CRITICAL ));then
    exitCode=$STATE_CRITICAL
    pluginOutput=$pluginOutput"CRITICAL : Max number of processes per user ($highestUser : $highestNbProcess) > Critical ($OPT_CRITICAL)"
elif (( $highestNbProcess >= $OPT_WARNING )) && (( $highestNbProcess < $OPT_CRITICAL ));then
    exitCode=$STATE_WARNING
    pluginOutput=$pluginOutput"WARNING : Warning ($OPT_WARNING) < Max number of processes per user ($highestUser : $highestNbProcess) < Critical ($OPT_CRITICAL)"
fi

exitPlugin "$pluginOutput" "$pluginPerfdata" $exitCode

# perfdata format :
#    'label'=value[UOM];[warn];[crit];[min];[max]
# source : http://nagiosplug.sourceforge.net/developer-guidelines.html#AEN201

########################################## ##########################################################
# the end!
########################################## ##########################################################
